# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-18.04

steps:
- task: Npm@1
  inputs:
    command: 'install'
    customRegistry: 'useFeed'
    customFeed: 'c2fbf450-750a-4471-aa3a-7172db9bb39b/35e964ea-fa5b-459b-b47b-a27ecdbfe0f9'
# - script: echo Hello, world!
#   displayName: 'Run a one-line script'
# - script: |
#     echo Add other tasks to build, test, and deploy your project.
#     echo See https://aka.ms/yaml
#   displayName: 'Run a multi-line script'
# - script: echo Hello, world $(ANYPOINT_HOST)
#   displayName: 'Run a one-line script'
- script: ./node_modules/.bin/api-catalog publish-asset --host='https://qax.anypoint.mulesoft.com' --username="$(ANYPOINT_USERNAME)" --password="$(ANYPOINT_PASSWORD)"
  displayName: 'Publish via 1-line'
# - task: Bash@3
#   inputs:
#     targetType: 'inline'
#     script: |
#       echo 'publishing...'
#       node --version
#       echo ./node_modules/.bin/api-catalog publish-asset --username="$(ANYPOINT_USERNAME)" --password="$(ANYPOINT_PASSWORD)"
#       ./node_modules/.bin/api-catalog publish-asset --username="$(ANYPOINT_USERNAME)" --password="$(ANYPOINT_PASSWORD)"