trigger:
- main

pool:
  vmImage: ubuntu-18.04

steps:
- task: Npm@1
  inputs:
    command: 'install'
    customRegistry: 'useFeed'
    customFeed: 'c2fbf450-750a-4471-aa3a-7172db9bb39b/35e964ea-fa5b-459b-b47b-a27ecdbfe0f9'

- script: ./node_modules/.bin/api-catalog publish-asset --host=$(ANYPOINT_HOST) --username="$(ANYPOINT_USERNAME)" --password="$(ANYPOINT_PASSWORD)"
  displayName: 'Publish APIs'